- name: Agriculture
- name: Arts
- name: Banking / Insurance / Finance
- name: Budget / Fiscal Policy / Taxes
- name: Business
- name: Campaign Finance / Elections / Politics
- name: Children / Families / Human Services
- name: Civil Rights & Liberties
- name: Climate / Environment
- name: Communications / Information / Internet
- name: Crime / Law Enforcement / Public Safety
- name: Demographics
- name: Economics / Monetary Policy
- name: Education
- name: Employment / Labor
- name: Energy / Natural Resources
- name: Foreign Commerce / Foreign Policy
- name: Geography / Geospatial
- name: Governance
- name: Health / Nutrition
- name: Housing / Urban
- name: Immigration
- name: Foreign Aid / International Development
- name: Law / Courts
- name: Metropolitan / Municipal
- name: National Security
- name: Philanthropy
- name: Poverty / Welfare
- name: Science & Technology / Innovation
- name: Stimulus / Economic Development
- name: Trade
- name: Transportation
- name: Travel / Recreation
- name: Utilities
- name: Veterans Affairs
